checkpoint: data/checkpoints/favorita/tft_erm/favorita_tft_erm_K3_50items_inclstatcat_adam_06-0.3928.ckpt

eval:
  is_maml: false
  run_name: "favorita_tft_erm_K3_50items_inclstatcat_adam_metatest"
  test_data: data/favorita/meta_sets/Seed42_store47_itemBased_meta_test_1000items_3107.pkl
  K: [3]
  support_window_size: 28
  adaptation_steps: 10
  inner_grad_clip: 100

